=== asmaagamal871/XML-labs/lab3/task1/employee.xsd
<?xml version="1.0" encoding="UTF-8"?>

<!-- W3C Schema generated by XMLSpy v2023 sp1 (x64) (http://www.altova.com) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="address">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="street"/>
				<xs:element ref="buildingNo"/>
				<xs:element ref="region"/>
				<xs:element ref="city"/>
				<xs:element ref="country"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="addresses">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="address"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="buildingNo">
		<xs:simpleType>
			<xs:restriction base="xs:byte">
				<xs:enumeration value="10"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="city">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="alexandria"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="country">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="egypt"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="email">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="asmaa@gmail.com"/>
				<xs:enumeration value="yara@gmail.com"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="emp">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="name"/>
				<xs:element ref="phones"/>
				<xs:element ref="addresses"/>
				<xs:element ref="email"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="employee">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="emp" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="name">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="asmaa"/>
				<xs:enumeration value="yara"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="phone">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="ST_phone">
					<xs:attribute name="type" use="required">
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:enumeration value="home"/>
								<xs:enumeration value="mobile"/>
								<xs:enumeration value="work"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="phones">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="phone" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="region">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="miami"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="street">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="street"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:simpleType name="ST_phone">
		<xs:restriction base="xs:long">
			<xs:enumeration value="12345678958"/>
			<xs:enumeration value="12458968793"/>
			<xs:enumeration value="1247859658"/>
			<xs:enumeration value="12548796368"/>
			<xs:enumeration value="14758963257"/>
			<xs:enumeration value="14859687523"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== asmaagamal871/XML-labs/lab3/task1/employee.xml
<?xml version="1.0" encoding="UTF-8"?>
<employee xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///D:/ITI/xml/lab3/task1/employee.xsd">
	<emp>
		<name>asmaa</name>
		<phones>
			<phone type="home">12345678958</phone>
			<phone type="work">12548796368</phone>
			<phone type="mobile">1247859658</phone>
		</phones>
		<addresses>
			<address>
				<street>street</street>
				<buildingNo>10</buildingNo>
				<region>miami</region>
				<city>alexandria</city>
				<country>egypt</country>
			</address>
		</addresses>
		<email>asmaa@gmail.com</email>
	</emp>
	<emp>
		<name>yara</name>
		<phones>
			<phone type="home">12458968793</phone>
			<phone type="work">14859687523</phone>
			<phone type="mobile">14758963257</phone>
		</phones>
		<addresses>
			<address>
				<street>street</street>
				<buildingNo>10</buildingNo>
				<region>miami</region>
				<city>alexandria</city>
				<country>egypt</country>
			</address>
		</addresses>
		<email>yara@gmail.com</email>
	</emp>
</employee>
